name 'flyway'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures flyway'
long_description 'Installs/Configures flyway'
version '0.1.0'
